# Created using wingetcreate 1.2.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: IObit.DriverBooster
PackageVersion: 10.5.0
MinimumOSVersion: 10.0.0.0
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- dbd
- dbop
Installers:
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://cdn.iobit.com/dl/driver_booster_setup.exe
  InstallerSha256: 10E881FD9F7EBFE20FCD580F5FC0BB9617CD62D01D347FDCB32C63DBE0F3DAC0
  ProductCode: Driver Booster_is1
  AppsAndFeaturesEntries:
  - DisplayName: Driver Booster 10
    ProductCode: Driver Booster_is1
ManifestType: installer
ManifestVersion: 1.4.0
